//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.socmut.be/ErrorHandling/2008/05", ClrNamespace="www.socmut.be.ErrorHandling._2008._05")]

namespace GW.VSB.THAB.Contracts.GetPersonsByCertificateState
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByCertificateStateRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonsByCertifi" +
        "cateState")]
    public partial class GetPersonsByCertificateStateRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AcceptedField;
        
        private bool PendingField;
        
        private System.DateTime ReferenceDecisionMonthField;
        
        private System.DateTime ReferenceStartMonthField;
        
        private bool RefusedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Accepted
        {
            get
            {
                return this.AcceptedField;
            }
            set
            {
                this.AcceptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pending
        {
            get
            {
                return this.PendingField;
            }
            set
            {
                this.PendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDecisionMonth
        {
            get
            {
                return this.ReferenceDecisionMonthField;
            }
            set
            {
                this.ReferenceDecisionMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceStartMonth
        {
            get
            {
                return this.ReferenceStartMonthField;
            }
            set
            {
                this.ReferenceStartMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Refused
        {
            get
            {
                return this.RefusedField;
            }
            set
            {
                this.RefusedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByCertificateStateResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonsByCertifi" +
        "cateState")]
    public partial class GetPersonsByCertificateStateResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long[] SinrsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Sinrs
        {
            get
            {
                return this.SinrsField;
            }
            set
            {
                this.SinrsField = value;
            }
        }
    }
}
namespace GW.Core.Messaging
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessage", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetThabDataResponse8avSXHVx))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetCertificatesResponsefjFlgFUb))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetPaymentsResponsekH_Pn8jcG))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetLettersResponseRT_S2fO0f))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetPersonalDataResponser1i1MAcW))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetRemarkResponse5o92LdDq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfSaveRemarkResponseZnlGTFiS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GW.Core.Messaging.ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S))]
    public partial class ReturnMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.Core.Messaging.Message[] BusinessMessagesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.Core.Messaging.Message[] BusinessMessages
        {
            get
            {
                return this.BusinessMessagesField;
            }
            set
            {
                this.BusinessMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetThabDataResponse8avSXHVx", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetThabDataResponse8avSXHVx : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetThabData.GetThabDataResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetThabData.GetThabDataResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetCertificatesResponsefjFlgFUb", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetCertificatesResponsefjFlgFUb : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetCertificates.GetCertificatesResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetCertificates.GetCertificatesResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetCertificates.GetCertificatesPayableAmountResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetCertificates.GetCertificatesPayableAmountResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPaymentsResponsekH_Pn8jcG", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPaymentsResponsekH_Pn8jcG : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetPayments.GetPaymentsResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetPayments.GetPaymentsResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetLettersResponseRT_S2fO0f", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetLettersResponseRT_S2fO0f : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Core.Read.GetLetters.GetLettersResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Core.Read.GetLetters.GetLettersResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetCertificateNotifications.GetCertificateNotificationsResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetCertificateNotifications.GetCertificateNotificationsResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPersonalDataResponser1i1MAcW", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPersonalDataResponser1i1MAcW : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetPersonalData.GetPersonalDataResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetPersonalData.GetPersonalDataResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetRemarkResponse5o92LdDq", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetRemarkResponse5o92LdDq : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetRemark.GetRemarkResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetRemark.GetRemarkResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfSaveRemarkResponseZnlGTFiS", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfSaveRemarkResponseZnlGTFiS : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.SaveRemark.SaveRemarkResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.SaveRemark.SaveRemarkResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S : GW.Core.Messaging.ReturnMessage
    {
        
        private GW.VSB.THAB.Contracts.GetPersonsByCertificateState.GetPersonsByCertificateStateResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.GetPersonsByCertificateState.GetPersonsByCertificateStateResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageStringField;
        
        private GW.Core.Messaging.MessageType TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageString
        {
            get
            {
                return this.MessageStringField;
            }
            set
            {
                this.MessageStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.Core.Messaging.MessageType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public enum MessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
}
namespace GW.VSB.THAB.Contracts.GetThabData
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetThabDataResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetThabData")]
    public partial class GetThabDataResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.ThabData[] ThabDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.ThabData[] ThabData
        {
            get
            {
                return this.ThabDataField;
            }
            set
            {
                this.ThabDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetThabDataRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetThabData")]
    public partial class GetThabDataRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InszField;
        
        private long SiNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Contracts.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThabData", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class ThabData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.Certificate CertificateField;
        
        private GW.VSB.THAB.Contracts.Data.CertificateNotifications CertificateNotificationsField;
        
        private GW.VSB.THAB.Contracts.Data.Letter[] LettersField;
        
        private GW.VSB.THAB.Contracts.Data.CertificatePayableAmount[] PayableAmountsField;
        
        private GW.VSB.THAB.Contracts.Data.Payment[] PaymentsField;
        
        private string RemarkField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Certificate Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.CertificateNotifications CertificateNotifications
        {
            get
            {
                return this.CertificateNotificationsField;
            }
            set
            {
                this.CertificateNotificationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Letter[] Letters
        {
            get
            {
                return this.LettersField;
            }
            set
            {
                this.LettersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.CertificatePayableAmount[] PayableAmounts
        {
            get
            {
                return this.PayableAmountsField;
            }
            set
            {
                this.PayableAmountsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certificate", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Certificate : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.DocumentLink CalculationBasicRightDocumentField;
        
        private System.Nullable<System.DateTime> DecisionDateField;
        
        private System.Nullable<System.DateTime> FromField;
        
        private string IdField;
        
        private System.DateTime InitialDateField;
        
        private System.Nullable<System.DateTime> MigrateDateField;
        
        private string ReasonClosureField;
        
        private System.Nullable<System.DateTime> RegistrationDateField;
        
        private string StateField;
        
        private System.Nullable<System.DateTime> UntilField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.DocumentLink CalculationBasicRightDocument
        {
            get
            {
                return this.CalculationBasicRightDocumentField;
            }
            set
            {
                this.CalculationBasicRightDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DecisionDate
        {
            get
            {
                return this.DecisionDateField;
            }
            set
            {
                this.DecisionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitialDate
        {
            get
            {
                return this.InitialDateField;
            }
            set
            {
                this.InitialDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MigrateDate
        {
            get
            {
                return this.MigrateDateField;
            }
            set
            {
                this.MigrateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonClosure
        {
            get
            {
                return this.ReasonClosureField;
            }
            set
            {
                this.ReasonClosureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Until
        {
            get
            {
                return this.UntilField;
            }
            set
            {
                this.UntilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificateNotifications", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class CertificateNotifications : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.NextStep nextStepField;
        
        private GW.VSB.THAB.Contracts.Data.Notification[] notificicationsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.NextStep nextStep
        {
            get
            {
                return this.nextStepField;
            }
            set
            {
                this.nextStepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Notification[] notificications
        {
            get
            {
                return this.notificicationsField;
            }
            set
            {
                this.notificicationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Letter", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Letter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CertificateIdField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateId
        {
            get
            {
                return this.CertificateIdField;
            }
            set
            {
                this.CertificateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificatePayableAmount", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class CertificatePayableAmount : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        private System.Nullable<System.DateTime> EndField;
        
        private System.Nullable<System.DateTime> StartField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.Account AccountField;
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private System.DateTime PeriodEndField;
        
        private System.DateTime PeriodStartField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        private int UnCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Account Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodEnd
        {
            get
            {
                return this.PeriodEndField;
            }
            set
            {
                this.PeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodStart
        {
            get
            {
                return this.PeriodStartField;
            }
            set
            {
                this.PeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnCode
        {
            get
            {
                return this.UnCodeField;
            }
            set
            {
                this.UnCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentLink", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class DocumentLink : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReferenceField;
        
        private string UniqueIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueId
        {
            get
            {
                return this.UniqueIdField;
            }
            set
            {
                this.UniqueIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NextStep", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class NextStep : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BicField;
        
        private string IbanField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bic
        {
            get
            {
                return this.BicField;
            }
            set
            {
                this.BicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban
        {
            get
            {
                return this.IbanField;
            }
            set
            {
                this.IbanField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalData", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class PersonalData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CityContactField;
        
        private int FederationField;
        
        private string FirstNameContactField;
        
        private string FirstNameMemberField;
        
        private short GenderMemberField;
        
        private string HouseNumberContactField;
        
        private string InszField;
        
        private string NameContactField;
        
        private string NameMemberField;
        
        private string NumberBoxContactField;
        
        private long SiNumberField;
        
        private string StreetContactField;
        
        private string ZipCodeContactField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityContact
        {
            get
            {
                return this.CityContactField;
            }
            set
            {
                this.CityContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Federation
        {
            get
            {
                return this.FederationField;
            }
            set
            {
                this.FederationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameContact
        {
            get
            {
                return this.FirstNameContactField;
            }
            set
            {
                this.FirstNameContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameMember
        {
            get
            {
                return this.FirstNameMemberField;
            }
            set
            {
                this.FirstNameMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short GenderMember
        {
            get
            {
                return this.GenderMemberField;
            }
            set
            {
                this.GenderMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumberContact
        {
            get
            {
                return this.HouseNumberContactField;
            }
            set
            {
                this.HouseNumberContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameContact
        {
            get
            {
                return this.NameContactField;
            }
            set
            {
                this.NameContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameMember
        {
            get
            {
                return this.NameMemberField;
            }
            set
            {
                this.NameMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberBoxContact
        {
            get
            {
                return this.NumberBoxContactField;
            }
            set
            {
                this.NumberBoxContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetContact
        {
            get
            {
                return this.StreetContactField;
            }
            set
            {
                this.StreetContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCodeContact
        {
            get
            {
                return this.ZipCodeContactField;
            }
            set
            {
                this.ZipCodeContactField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Contracts.GetCertificates
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.Certificate[] CertificatesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Certificate[] Certificates
        {
            get
            {
                return this.CertificatesField;
            }
            set
            {
                this.CertificatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesPayableAmountResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesPayableAmountResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.CertificatePayableAmount[] PayableAmountsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.CertificatePayableAmount[] PayableAmounts
        {
            get
            {
                return this.PayableAmountsField;
            }
            set
            {
                this.PayableAmountsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InszField;
        
        private long SiNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesPayableAmountRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesPayableAmountRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private long SiNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Contracts.GetPayments
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPayments")]
    public partial class GetPaymentsResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.Payment[] PaymentsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPayments")]
    public partial class GetPaymentsRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ReferenceDateField;
        
        private decimal SiNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Core.Read.GetLetters
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLettersResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Core.Read.GetLetters")]
    public partial class GetLettersResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.Letter[] LettersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.Letter[] Letters
        {
            get
            {
                return this.LettersField;
            }
            set
            {
                this.LettersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLettersRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Core.Read.GetLetters")]
    public partial class GetLettersRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CertificateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateId
        {
            get
            {
                return this.CertificateIdField;
            }
            set
            {
                this.CertificateIdField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Contracts.GetCertificateNotifications
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificateNotificationsResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificateNotif" +
        "ications")]
    public partial class GetCertificateNotificationsResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.CertificateNotifications CertificateNotificationsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.CertificateNotifications CertificateNotifications
        {
            get
            {
                return this.CertificateNotificationsField;
            }
            set
            {
                this.CertificateNotificationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificateNotificationsRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificateNotif" +
        "ications")]
    public partial class GetCertificateNotificationsRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CertificateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateId
        {
            get
            {
                return this.CertificateIdField;
            }
            set
            {
                this.CertificateIdField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Contracts.GetPersonalData
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonalDataResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonalData")]
    public partial class GetPersonalDataResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GW.VSB.THAB.Contracts.Data.PersonalData PersonalDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GW.VSB.THAB.Contracts.Data.PersonalData PersonalData
        {
            get
            {
                return this.PersonalDataField;
            }
            set
            {
                this.PersonalDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonalDataRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonalData")]
    public partial class GetPersonalDataRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long SiNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Contracts.GetRemark
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRemarkResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetRemark")]
    public partial class GetRemarkResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RemarkField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRemarkRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetRemark")]
    public partial class GetRemarkRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ReferenceDateField;
        
        private decimal SiNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
}
namespace GW.VSB.THAB.Contracts.SaveRemark
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRemarkResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.SaveRemark")]
    public partial class SaveRemarkResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SavedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Saved
        {
            get
            {
                return this.SavedField;
            }
            set
            {
                this.SavedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRemarkRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.SaveRemark")]
    public partial class SaveRemarkRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ReferenceDateField;
        
        private string RemarkField;
        
        private long SinrField;
        
        private string UseridField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Sinr
        {
            get
            {
                return this.SinrField;
            }
            set
            {
                this.SinrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Userid
        {
            get
            {
                return this.UseridField;
            }
            set
            {
                this.UseridField = value;
            }
        }
    }
}
namespace www.socmut.be.ErrorHandling._2008._05
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.socmut.be.ErrorHandling._2008._05.FaultMessage[] MessagesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public www.socmut.be.ErrorHandling._2008._05.FaultMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SourceField;
        
        private string TagField;
        
        private www.socmut.be.ErrorHandling._2008._05.MessageText[] TranslationsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public www.socmut.be.ErrorHandling._2008._05.MessageText[] Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageText", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class MessageText : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CultureField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12", ConfigurationName="IThabService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
public interface IThabService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PersonsByCertificateState", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PersonsByCertificateStateResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PersonsByCertificateStateFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S GetPersonsByCertificateState(GW.VSB.THAB.Contracts.GetPersonsByCertificateState.GetPersonsByCertificateStateRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "ThabData", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "ThabDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "ThabDataFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetThabDataResponse8avSXHVx GetThabData(GW.VSB.THAB.Contracts.GetThabData.GetThabDataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "Certificates", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificatesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificatesFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetCertificatesResponsefjFlgFUb GetCertificates(GW.VSB.THAB.Contracts.GetCertificates.GetCertificatesRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificatesPayableAmounts", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificatesPayableAmountsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificatesPayableAmountsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb GetCertificatesPayableAmounts(GW.VSB.THAB.Contracts.GetCertificates.GetCertificatesPayableAmountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "Payments", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PaymentsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PaymentsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetPaymentsResponsekH_Pn8jcG GetPayments(GW.VSB.THAB.Contracts.GetPayments.GetPaymentsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "Letters", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "LettersResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "LettersFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetLettersResponseRT_S2fO0f GetLetters(GW.VSB.THAB.Core.Read.GetLetters.GetLettersRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificateNotifications", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificateNotificationsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "CertificateNotificationsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc GetCertificateNotifications(GW.VSB.THAB.Contracts.GetCertificateNotifications.GetCertificateNotificationsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PersonalData", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PersonalDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "PersonalDataFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetPersonalDataResponser1i1MAcW GetPersonalData(GW.VSB.THAB.Contracts.GetPersonalData.GetPersonalDataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "Remark", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "RemarkResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
        "RemarkFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfGetRemarkResponse5o92LdDq GetRemark(GW.VSB.THAB.Contracts.GetRemark.GetRemarkRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Sav" +
        "eRemark", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Sav" +
        "eRemarkResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.socmut.be.ErrorHandling._2008._05.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Sav" +
        "eRemarkFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    GW.Core.Messaging.ReturnMessageOfSaveRemarkResponseZnlGTFiS SaveRemark(GW.VSB.THAB.Contracts.SaveRemark.SaveRemarkRequest request);
}
