//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZvzService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByWarrantiesStateRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetPersonsByWarranti" +
        "esState")]
    public partial class GetPersonsByWarrantiesStateRequest : object
    {
        
        private bool AcceptedField;
        
        private bool PendingField;
        
        private System.DateTime ReferenceDecisionMonthField;
        
        private System.DateTime ReferenceStartMonthField;
        
        private bool RefusedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Accepted
        {
            get
            {
                return this.AcceptedField;
            }
            set
            {
                this.AcceptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pending
        {
            get
            {
                return this.PendingField;
            }
            set
            {
                this.PendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDecisionMonth
        {
            get
            {
                return this.ReferenceDecisionMonthField;
            }
            set
            {
                this.ReferenceDecisionMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceStartMonth
        {
            get
            {
                return this.ReferenceStartMonthField;
            }
            set
            {
                this.ReferenceStartMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Refused
        {
            get
            {
                return this.RefusedField;
            }
            set
            {
                this.RefusedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessage", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZvzService.ReturnMessageOfGetLastContractResponseKpGShgWr))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZvzService.ReturnMessageOfGetContributionsResponseJaCt47Ra))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZvzService.ReturnMessageOfGetWarrantiesResponsecEfhslJU))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZvzService.ReturnMessageOfGetPaymentsResponseVkdlAkLR))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZvzService.ReturnMessageOfGetZVZDataResponseTS9yuov7))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZvzService.ReturnMessageOfGetDecisionLettersResponse_PomNqTZT))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZvzService.ReturnMessageOfGetPersonsByWarrantiesStateResponseglHfjMZn))]
    public partial class ReturnMessage : object
    {
        
        private ZvzService.Message[] BusinessMessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Message[] BusinessMessages
        {
            get
            {
                return this.BusinessMessagesField;
            }
            set
            {
                this.BusinessMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetLastContractResponseKpGShgWr", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetLastContractResponseKpGShgWr : ZvzService.ReturnMessage
    {
        
        private ZvzService.GetLastContractResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.GetLastContractResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetContributionsResponseJaCt47Ra", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetContributionsResponseJaCt47Ra : ZvzService.ReturnMessage
    {
        
        private ZvzService.GetContributionsResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.GetContributionsResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetWarrantiesResponsecEfhslJU", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetWarrantiesResponsecEfhslJU : ZvzService.ReturnMessage
    {
        
        private ZvzService.GetWarrantiesResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.GetWarrantiesResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPaymentsResponseVkdlAkLR", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPaymentsResponseVkdlAkLR : ZvzService.ReturnMessage
    {
        
        private ZvzService.GetPaymentsResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.GetPaymentsResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetZVZDataResponseTS9yuov7", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetZVZDataResponseTS9yuov7 : ZvzService.ReturnMessage
    {
        
        private ZvzService.GetZVZDataResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.GetZVZDataResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetDecisionLettersResponse_PomNqTZT", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetDecisionLettersResponse_PomNqTZT : ZvzService.ReturnMessage
    {
        
        private ZvzService.GetDecisionLettersResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.GetDecisionLettersResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPersonsByWarrantiesStateResponseglHfjMZn", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPersonsByWarrantiesStateResponseglHfjMZn : ZvzService.ReturnMessage
    {
        
        private ZvzService.GetPersonsByWarrantiesStateResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.GetPersonsByWarrantiesStateResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class Message : object
    {
        
        private string MessageStringField;
        
        private ZvzService.MessageType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageString
        {
            get
            {
                return this.MessageStringField;
            }
            set
            {
                this.MessageStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.MessageType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByWarrantiesStateResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetPersonsByWarranti" +
        "esState")]
    public partial class GetPersonsByWarrantiesStateResponse : object
    {
        
        private long[] SinrsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Sinrs
        {
            get
            {
                return this.SinrsField;
            }
            set
            {
                this.SinrsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public enum MessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLastContractResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetLastContract")]
    public partial class GetLastContractResponse : object
    {
        
        private ZvzService.Contract LastContractField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Contract LastContract
        {
            get
            {
                return this.LastContractField;
            }
            set
            {
                this.LastContractField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class Contract : object
    {
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private string EndMotivationField;
        
        private string EndReasonField;
        
        private System.Nullable<System.DateTime> RequestDateField;
        
        private System.DateTime StartDateField;
        
        private string StartMotivationField;
        
        private string StartReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndMotivation
        {
            get
            {
                return this.EndMotivationField;
            }
            set
            {
                this.EndMotivationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndReason
        {
            get
            {
                return this.EndReasonField;
            }
            set
            {
                this.EndReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RequestDate
        {
            get
            {
                return this.RequestDateField;
            }
            set
            {
                this.RequestDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartMotivation
        {
            get
            {
                return this.StartMotivationField;
            }
            set
            {
                this.StartMotivationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartReason
        {
            get
            {
                return this.StartReasonField;
            }
            set
            {
                this.StartReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContributionsResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetContributions")]
    public partial class GetContributionsResponse : object
    {
        
        private ZvzService.Contribution[] ContributionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Contribution[] Contributions
        {
            get
            {
                return this.ContributionsField;
            }
            set
            {
                this.ContributionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contribution", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class Contribution : object
    {
        
        private decimal AmountField;
        
        private string CircuitField;
        
        private string CurrencyField;
        
        private System.Nullable<System.DateTime> PaymentDateField;
        
        private string StateField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Circuit
        {
            get
            {
                return this.CircuitField;
            }
            set
            {
                this.CircuitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                this.PaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetWarrantiesResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetWarranties")]
    public partial class GetWarrantiesResponse : object
    {
        
        private ZvzService.Warranty[] WarrantiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Warranty[] Warranties
        {
            get
            {
                return this.WarrantiesField;
            }
            set
            {
                this.WarrantiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Warranty", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class Warranty : object
    {
        
        private string CareField;
        
        private string CertificateField;
        
        private System.Nullable<System.DateTime> DateFromField;
        
        private System.Nullable<System.DateTime> DateUntilField;
        
        private System.Nullable<System.DateTime> DecisionDateField;
        
        private string RefusalReasonField;
        
        private System.DateTime RequestDateField;
        
        private string ScaleField;
        
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Care
        {
            get
            {
                return this.CareField;
            }
            set
            {
                this.CareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateFrom
        {
            get
            {
                return this.DateFromField;
            }
            set
            {
                this.DateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUntil
        {
            get
            {
                return this.DateUntilField;
            }
            set
            {
                this.DateUntilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DecisionDate
        {
            get
            {
                return this.DecisionDateField;
            }
            set
            {
                this.DecisionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefusalReason
        {
            get
            {
                return this.RefusalReasonField;
            }
            set
            {
                this.RefusalReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate
        {
            get
            {
                return this.RequestDateField;
            }
            set
            {
                this.RequestDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Scale
        {
            get
            {
                return this.ScaleField;
            }
            set
            {
                this.ScaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetPayments")]
    public partial class GetPaymentsResponse : object
    {
        
        private ZvzService.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class Payment : object
    {
        
        private ZvzService.Account AccountField;
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private System.DateTime PeriodEndField;
        
        private System.DateTime PeriodStartField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        private int UnCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Account Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodEnd
        {
            get
            {
                return this.PeriodEndField;
            }
            set
            {
                this.PeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodStart
        {
            get
            {
                return this.PeriodStartField;
            }
            set
            {
                this.PeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnCode
        {
            get
            {
                return this.UnCodeField;
            }
            set
            {
                this.UnCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class Account : object
    {
        
        private string BicField;
        
        private string IbanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bic
        {
            get
            {
                return this.BicField;
            }
            set
            {
                this.BicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban
        {
            get
            {
                return this.IbanField;
            }
            set
            {
                this.IbanField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetZVZDataResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetZVZData")]
    public partial class GetZVZDataResponse : object
    {
        
        private ZvzService.ZVZData ZVZDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.ZVZData ZVZData
        {
            get
            {
                return this.ZVZDataField;
            }
            set
            {
                this.ZVZDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZVZData", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class ZVZData : object
    {
        
        private ZvzService.Contribution[] ContributionsField;
        
        private ZvzService.DecisionLetter[] DecisionLettersField;
        
        private ZvzService.Contract LastContractField;
        
        private ZvzService.ZVZWarranty[] ZVZWarrantiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Contribution[] Contributions
        {
            get
            {
                return this.ContributionsField;
            }
            set
            {
                this.ContributionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.DecisionLetter[] DecisionLetters
        {
            get
            {
                return this.DecisionLettersField;
            }
            set
            {
                this.DecisionLettersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Contract LastContract
        {
            get
            {
                return this.LastContractField;
            }
            set
            {
                this.LastContractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.ZVZWarranty[] ZVZWarranties
        {
            get
            {
                return this.ZVZWarrantiesField;
            }
            set
            {
                this.ZVZWarrantiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecisionLetter", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class DecisionLetter : object
    {
        
        private System.Nullable<System.DateTime> SendedDateField;
        
        private string TypeField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendedDate
        {
            get
            {
                return this.SendedDateField;
            }
            set
            {
                this.SendedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZVZWarranty", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.Data")]
    public partial class ZVZWarranty : object
    {
        
        private ZvzService.Payment[] PaymentsField;
        
        private ZvzService.Warranty WarrantyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.Warranty Warranty
        {
            get
            {
                return this.WarrantyField;
            }
            set
            {
                this.WarrantyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDecisionLettersResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetDecisionLetters")]
    public partial class GetDecisionLettersResponse : object
    {
        
        private ZvzService.DecisionLetter[] DecisionLettersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZvzService.DecisionLetter[] DecisionLetters
        {
            get
            {
                return this.DecisionLettersField;
            }
            set
            {
                this.DecisionLettersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultDetail : object
    {
        
        private ZvzService.FaultMessage[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ZvzService.FaultMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultMessage : object
    {
        
        private string SourceField;
        
        private string TagField;
        
        private ZvzService.MessageText[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ZvzService.MessageText[] Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageText", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class MessageText : object
    {
        
        private string CultureField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLastContractRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetLastContract")]
    public partial class GetLastContractRequest : object
    {
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContributionsRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetContributions")]
    public partial class GetContributionsRequest : object
    {
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetWarrantiesRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetWarranties")]
    public partial class GetWarrantiesRequest : object
    {
        
        private decimal SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetPayments")]
    public partial class GetPaymentsRequest : object
    {
        
        private System.DateTime ReferenceDateField;
        
        private decimal SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetZVZDataRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetZVZData")]
    public partial class GetZVZDataRequest : object
    {
        
        private System.DateTime BirthDateField;
        
        private short FedField;
        
        private int FedNumberField;
        
        private int SexField;
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Fed
        {
            get
            {
                return this.FedField;
            }
            set
            {
                this.FedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FedNumber
        {
            get
            {
                return this.FedNumberField;
            }
            set
            {
                this.FedNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDecisionLettersRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.ZVZ.Contracts.GetDecisionLetters")]
    public partial class GetDecisionLettersRequest : object
    {
        
        private System.DateTime BirthDateField;
        
        private short FedField;
        
        private int FedNumberField;
        
        private int SexField;
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Fed
        {
            get
            {
                return this.FedField;
            }
            set
            {
                this.FedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FedNumber
        {
            get
            {
                return this.FedNumberField;
            }
            set
            {
                this.FedNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09", ConfigurationName="ZvzService.IZvzService")]
    public interface IZvzService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetPe" +
            "rsonsByWarrantiesState", ReplyAction="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetPe" +
            "rsonsByWarrantiesStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ZvzService.FaultDetail), Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetPe" +
            "rsonsByWarrantiesStateFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetPersonsByWarrantiesStateResponseglHfjMZn> GetPersonsByWarrantiesStateAsync(ZvzService.GetPersonsByWarrantiesStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetCo" +
            "ntract", ReplyAction="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetCo" +
            "ntractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ZvzService.FaultDetail), Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetCo" +
            "ntractFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetLastContractResponseKpGShgWr> GetContractAsync(ZvzService.GetLastContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetCo" +
            "ntributions", ReplyAction="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetCo" +
            "ntributionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ZvzService.FaultDetail), Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetCo" +
            "ntributionsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetContributionsResponseJaCt47Ra> GetContributionsAsync(ZvzService.GetContributionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetWa" +
            "rranties", ReplyAction="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetWa" +
            "rrantiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ZvzService.FaultDetail), Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetWa" +
            "rrantiesFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetWarrantiesResponsecEfhslJU> GetWarrantiesAsync(ZvzService.GetWarrantiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetPa" +
            "yments", ReplyAction="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetPa" +
            "ymentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ZvzService.FaultDetail), Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetPa" +
            "ymentsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetPaymentsResponseVkdlAkLR> GetPaymentsAsync(ZvzService.GetPaymentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetZV" +
            "ZData", ReplyAction="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetZV" +
            "ZDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ZvzService.FaultDetail), Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetZV" +
            "ZDataFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetZVZDataResponseTS9yuov7> GetZVZDataAsync(ZvzService.GetZVZDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetDe" +
            "cisionLetter", ReplyAction="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetDe" +
            "cisionLetterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ZvzService.FaultDetail), Action="http://MutSocMut/GW.VSB.ZVZ.Service.Contracts.Data/Data/2016/09/IZvzService/GetDe" +
            "cisionLetterFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetDecisionLettersResponse_PomNqTZT> GetDecisionLetterAsync(ZvzService.GetDecisionLettersRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IZvzServiceChannel : ZvzService.IZvzService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class ZvzServiceClient : System.ServiceModel.ClientBase<ZvzService.IZvzService>, ZvzService.IZvzService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZvzServiceClient() : 
                base(ZvzServiceClient.GetDefaultBinding(), ZvzServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IZvzService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZvzServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ZvzServiceClient.GetBindingForEndpoint(endpointConfiguration), ZvzServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZvzServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZvzServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZvzServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZvzServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZvzServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetPersonsByWarrantiesStateResponseglHfjMZn> GetPersonsByWarrantiesStateAsync(ZvzService.GetPersonsByWarrantiesStateRequest request)
        {
            return base.Channel.GetPersonsByWarrantiesStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetLastContractResponseKpGShgWr> GetContractAsync(ZvzService.GetLastContractRequest request)
        {
            return base.Channel.GetContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetContributionsResponseJaCt47Ra> GetContributionsAsync(ZvzService.GetContributionsRequest request)
        {
            return base.Channel.GetContributionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetWarrantiesResponsecEfhslJU> GetWarrantiesAsync(ZvzService.GetWarrantiesRequest request)
        {
            return base.Channel.GetWarrantiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetPaymentsResponseVkdlAkLR> GetPaymentsAsync(ZvzService.GetPaymentsRequest request)
        {
            return base.Channel.GetPaymentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetZVZDataResponseTS9yuov7> GetZVZDataAsync(ZvzService.GetZVZDataRequest request)
        {
            return base.Channel.GetZVZDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZvzService.ReturnMessageOfGetDecisionLettersResponse_PomNqTZT> GetDecisionLetterAsync(ZvzService.GetDecisionLettersRequest request)
        {
            return base.Channel.GetDecisionLetterAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZvzService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZvzService))
            {
                return new System.ServiceModel.EndpointAddress("http://ws-test3.sm-ms.lan/GW.VSB.ZVZ.WcfService/WcfService/ZvzService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZvzServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IZvzService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZvzServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IZvzService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IZvzService,
        }
    }
}
