//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsbService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRemarkRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.GetRemark")]
    public partial class GetRemarkRequest : object
    {
        
        private long SinrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Sinr
        {
            get
            {
                return this.SinrField;
            }
            set
            {
                this.SinrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessage", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VsbService.ReturnMessageOfSaveRemarkResponsesd4Dd1KL))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VsbService.ReturnMessageOfSaveReturnCalculationResponsenW6QCFDE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VsbService.ReturnMessageOfGetReturnCalculationResponsenW6QCFDE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VsbService.ReturnMessageOfboolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VsbService.ReturnMessageOfGetRemarkResponseyiBlrIzk))]
    public partial class ReturnMessage : object
    {
        
        private VsbService.Message[] BusinessMessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.Message[] BusinessMessages
        {
            get
            {
                return this.BusinessMessagesField;
            }
            set
            {
                this.BusinessMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfSaveRemarkResponsesd4Dd1KL", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfSaveRemarkResponsesd4Dd1KL : VsbService.ReturnMessage
    {
        
        private VsbService.SaveRemarkResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.SaveRemarkResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfSaveReturnCalculationResponsenW6QCFDE", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfSaveReturnCalculationResponsenW6QCFDE : VsbService.ReturnMessage
    {
        
        private VsbService.SaveReturnCalculationResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.SaveReturnCalculationResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetReturnCalculationResponsenW6QCFDE", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetReturnCalculationResponsenW6QCFDE : VsbService.ReturnMessage
    {
        
        private VsbService.GetReturnCalculationResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.GetReturnCalculationResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfboolean", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfboolean : VsbService.ReturnMessage
    {
        
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetRemarkResponseyiBlrIzk", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetRemarkResponseyiBlrIzk : VsbService.ReturnMessage
    {
        
        private VsbService.GetRemarkResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.GetRemarkResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class Message : object
    {
        
        private string MessageStringField;
        
        private VsbService.MessageType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageString
        {
            get
            {
                return this.MessageStringField;
            }
            set
            {
                this.MessageStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.MessageType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRemarkResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.GetRemark")]
    public partial class GetRemarkResponse : object
    {
        
        private string RemarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public enum MessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRemarkResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.SaveRemark")]
    public partial class SaveRemarkResponse : object
    {
        
        private bool savedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool saved
        {
            get
            {
                return this.savedField;
            }
            set
            {
                this.savedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveReturnCalculationResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.ReturnCalculation")]
    public partial class SaveReturnCalculationResponse : object
    {
        
        private long ReturnCalculationIdField;
        
        private long SiNumberField;
        
        private bool SucceededField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReturnCalculationId
        {
            get
            {
                return this.ReturnCalculationIdField;
            }
            set
            {
                this.ReturnCalculationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succeeded
        {
            get
            {
                return this.SucceededField;
            }
            set
            {
                this.SucceededField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReturnCalculationResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.ReturnCalculation")]
    public partial class GetReturnCalculationResponse : object
    {
        
        private System.DateTime CreateDateField;
        
        private string CreatedByField;
        
        private int FederationNumberField;
        
        private string InszField;
        
        private bool IsErrorField;
        
        private bool IsFraudeField;
        
        private System.DateTime ObjectionDateField;
        
        private bool ObjectionMadeField;
        
        private string ReasonField;
        
        private System.DateTime RegularLetterCreateDateField;
        
        private string RegularLetterCreatedByField;
        
        private string RemarkField;
        
        private decimal ReturnByBOBField;
        
        private decimal ReturnByDeductionField;
        
        private decimal ReturnByOGMField;
        
        private decimal ReturnByTHABField;
        
        private decimal ReturnByZVZField;
        
        private long ReturnCalculationIdField;
        
        private VsbService.ReturnCalculationLine[] ReturnLinesField;
        
        private bool ReturnStartedField;
        
        private long SiNumberField;
        
        private System.DateTime SignedLetterCreateDateField;
        
        private string SignedLetterCreatedByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FederationNumber
        {
            get
            {
                return this.FederationNumberField;
            }
            set
            {
                this.FederationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError
        {
            get
            {
                return this.IsErrorField;
            }
            set
            {
                this.IsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFraude
        {
            get
            {
                return this.IsFraudeField;
            }
            set
            {
                this.IsFraudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ObjectionDate
        {
            get
            {
                return this.ObjectionDateField;
            }
            set
            {
                this.ObjectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ObjectionMade
        {
            get
            {
                return this.ObjectionMadeField;
            }
            set
            {
                this.ObjectionMadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegularLetterCreateDate
        {
            get
            {
                return this.RegularLetterCreateDateField;
            }
            set
            {
                this.RegularLetterCreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegularLetterCreatedBy
        {
            get
            {
                return this.RegularLetterCreatedByField;
            }
            set
            {
                this.RegularLetterCreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByBOB
        {
            get
            {
                return this.ReturnByBOBField;
            }
            set
            {
                this.ReturnByBOBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByDeduction
        {
            get
            {
                return this.ReturnByDeductionField;
            }
            set
            {
                this.ReturnByDeductionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByOGM
        {
            get
            {
                return this.ReturnByOGMField;
            }
            set
            {
                this.ReturnByOGMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByTHAB
        {
            get
            {
                return this.ReturnByTHABField;
            }
            set
            {
                this.ReturnByTHABField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByZVZ
        {
            get
            {
                return this.ReturnByZVZField;
            }
            set
            {
                this.ReturnByZVZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReturnCalculationId
        {
            get
            {
                return this.ReturnCalculationIdField;
            }
            set
            {
                this.ReturnCalculationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.ReturnCalculationLine[] ReturnLines
        {
            get
            {
                return this.ReturnLinesField;
            }
            set
            {
                this.ReturnLinesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnStarted
        {
            get
            {
                return this.ReturnStartedField;
            }
            set
            {
                this.ReturnStartedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignedLetterCreateDate
        {
            get
            {
                return this.SignedLetterCreateDateField;
            }
            set
            {
                this.SignedLetterCreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignedLetterCreatedBy
        {
            get
            {
                return this.SignedLetterCreatedByField;
            }
            set
            {
                this.SignedLetterCreatedByField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnCalculationLine", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.ReturnCalculation")]
    public partial class ReturnCalculationLine : object
    {
        
        private VsbService.ReturnCalculationKind KindField;
        
        private VsbService.ReturnCalculationPayment[] PaymentLinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.ReturnCalculationKind Kind
        {
            get
            {
                return this.KindField;
            }
            set
            {
                this.KindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.ReturnCalculationPayment[] PaymentLines
        {
            get
            {
                return this.PaymentLinesField;
            }
            set
            {
                this.PaymentLinesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnCalculationKind", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.ReturnCalculation")]
    public enum ReturnCalculationKind : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZVZ = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THAB = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnCalculationPayment", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.ReturnCalculation")]
    public partial class ReturnCalculationPayment : object
    {
        
        private decimal AmountField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private int UnCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnCode
        {
            get
            {
                return this.UnCodeField;
            }
            set
            {
                this.UnCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultDetail : object
    {
        
        private VsbService.FaultMessage[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public VsbService.FaultMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultMessage : object
    {
        
        private string SourceField;
        
        private string TagField;
        
        private VsbService.MessageText[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public VsbService.MessageText[] Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageText", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class MessageText : object
    {
        
        private string CultureField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRemarkRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.SaveRemark")]
    public partial class SaveRemarkRequest : object
    {
        
        private string RemarkField;
        
        private long SinrField;
        
        private string UseridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Sinr
        {
            get
            {
                return this.SinrField;
            }
            set
            {
                this.SinrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Userid
        {
            get
            {
                return this.UseridField;
            }
            set
            {
                this.UseridField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveReturnCalculationRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.VSB.Contracts.ReturnCalculation")]
    public partial class SaveReturnCalculationRequest : object
    {
        
        private string CreatedByField;
        
        private int FederationNumberField;
        
        private string InszField;
        
        private bool IsErrorField;
        
        private bool IsFraudeField;
        
        private System.DateTime ObjectionDateField;
        
        private bool ObjectionMadeField;
        
        private string ReasonField;
        
        private System.Nullable<System.DateTime> RegularLetterCreateDateField;
        
        private string RegularLetterCreatedByField;
        
        private string RemarkField;
        
        private decimal ReturnByBOBField;
        
        private decimal ReturnByDeductionField;
        
        private decimal ReturnByOGMField;
        
        private decimal ReturnByTHABField;
        
        private decimal ReturnByZVZField;
        
        private System.Nullable<long> ReturnCalculationIdField;
        
        private VsbService.ReturnCalculationLine[] ReturnLinesField;
        
        private long SiNumberField;
        
        private System.Nullable<System.DateTime> SignedLetterCreateDateField;
        
        private string SignedLetterCreatedByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FederationNumber
        {
            get
            {
                return this.FederationNumberField;
            }
            set
            {
                this.FederationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError
        {
            get
            {
                return this.IsErrorField;
            }
            set
            {
                this.IsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFraude
        {
            get
            {
                return this.IsFraudeField;
            }
            set
            {
                this.IsFraudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ObjectionDate
        {
            get
            {
                return this.ObjectionDateField;
            }
            set
            {
                this.ObjectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ObjectionMade
        {
            get
            {
                return this.ObjectionMadeField;
            }
            set
            {
                this.ObjectionMadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegularLetterCreateDate
        {
            get
            {
                return this.RegularLetterCreateDateField;
            }
            set
            {
                this.RegularLetterCreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegularLetterCreatedBy
        {
            get
            {
                return this.RegularLetterCreatedByField;
            }
            set
            {
                this.RegularLetterCreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByBOB
        {
            get
            {
                return this.ReturnByBOBField;
            }
            set
            {
                this.ReturnByBOBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByDeduction
        {
            get
            {
                return this.ReturnByDeductionField;
            }
            set
            {
                this.ReturnByDeductionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByOGM
        {
            get
            {
                return this.ReturnByOGMField;
            }
            set
            {
                this.ReturnByOGMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByTHAB
        {
            get
            {
                return this.ReturnByTHABField;
            }
            set
            {
                this.ReturnByTHABField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnByZVZ
        {
            get
            {
                return this.ReturnByZVZField;
            }
            set
            {
                this.ReturnByZVZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ReturnCalculationId
        {
            get
            {
                return this.ReturnCalculationIdField;
            }
            set
            {
                this.ReturnCalculationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VsbService.ReturnCalculationLine[] ReturnLines
        {
            get
            {
                return this.ReturnLinesField;
            }
            set
            {
                this.ReturnLinesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SignedLetterCreateDate
        {
            get
            {
                return this.SignedLetterCreateDateField;
            }
            set
            {
                this.SignedLetterCreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignedLetterCreatedBy
        {
            get
            {
                return this.SignedLetterCreatedByField;
            }
            set
            {
                this.SignedLetterCreatedByField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01", ConfigurationName="VsbService.IVsbService")]
    public interface IVsbService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/GetRe" +
            "mark", ReplyAction="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/GetRe" +
            "markResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsbService.FaultDetail), Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/GetRe" +
            "markFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<VsbService.ReturnMessageOfGetRemarkResponseyiBlrIzk> GetRemarkAsync(VsbService.GetRemarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/SaveR" +
            "emark", ReplyAction="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/SaveR" +
            "emarkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsbService.FaultDetail), Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/SaveR" +
            "emarkFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<VsbService.ReturnMessageOfSaveRemarkResponsesd4Dd1KL> SaveRemarkAsync(VsbService.SaveRemarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/Upser" +
            "tReturnCalculation", ReplyAction="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/Upser" +
            "tReturnCalculationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsbService.FaultDetail), Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/Upser" +
            "tReturnCalculationFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<VsbService.ReturnMessageOfSaveReturnCalculationResponsenW6QCFDE> UpsertReturnCalculationAsync(VsbService.SaveReturnCalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/GetRe" +
            "turnCalculation", ReplyAction="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/GetRe" +
            "turnCalculationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsbService.FaultDetail), Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/GetRe" +
            "turnCalculationFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<VsbService.ReturnMessageOfGetReturnCalculationResponsenW6QCFDE> GetReturnCalculationAsync(long SiNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/Delet" +
            "eReturnCalculation", ReplyAction="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/Delet" +
            "eReturnCalculationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsbService.FaultDetail), Action="http://MutSocMut/GW.VSB.VSB.Service.Contracts.Data/Data/2017/01/IVsbService/Delet" +
            "eReturnCalculationFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<VsbService.ReturnMessageOfboolean> DeleteReturnCalculationAsync(long SiNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IVsbServiceChannel : VsbService.IVsbService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class VsbServiceClient : System.ServiceModel.ClientBase<VsbService.IVsbService>, VsbService.IVsbService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VsbServiceClient() : 
                base(VsbServiceClient.GetDefaultBinding(), VsbServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVsbService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VsbServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VsbServiceClient.GetBindingForEndpoint(endpointConfiguration), VsbServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VsbServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VsbServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VsbServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VsbServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VsbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VsbService.ReturnMessageOfGetRemarkResponseyiBlrIzk> GetRemarkAsync(VsbService.GetRemarkRequest request)
        {
            return base.Channel.GetRemarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsbService.ReturnMessageOfSaveRemarkResponsesd4Dd1KL> SaveRemarkAsync(VsbService.SaveRemarkRequest request)
        {
            return base.Channel.SaveRemarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsbService.ReturnMessageOfSaveReturnCalculationResponsenW6QCFDE> UpsertReturnCalculationAsync(VsbService.SaveReturnCalculationRequest request)
        {
            return base.Channel.UpsertReturnCalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsbService.ReturnMessageOfGetReturnCalculationResponsenW6QCFDE> GetReturnCalculationAsync(long SiNumber)
        {
            return base.Channel.GetReturnCalculationAsync(SiNumber);
        }
        
        public System.Threading.Tasks.Task<VsbService.ReturnMessageOfboolean> DeleteReturnCalculationAsync(long SiNumber)
        {
            return base.Channel.DeleteReturnCalculationAsync(SiNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVsbService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVsbService))
            {
                return new System.ServiceModel.EndpointAddress("http://ws-test3.sm-ms.lan/GW.VSB.VSB.WcfService/WcfService/VsbService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VsbServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVsbService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VsbServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVsbService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVsbService,
        }
    }
}
