//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByCertificateStateRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetPersonsByCertific" +
        "ateState")]
    public partial class GetPersonsByCertificateStateRequest : object
    {
        
        private bool AcceptedField;
        
        private bool PendingField;
        
        private System.DateTime ReferenceDecisionMonthField;
        
        private System.DateTime ReferenceStartMonthField;
        
        private bool RefusedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Accepted
        {
            get
            {
                return this.AcceptedField;
            }
            set
            {
                this.AcceptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pending
        {
            get
            {
                return this.PendingField;
            }
            set
            {
                this.PendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDecisionMonth
        {
            get
            {
                return this.ReferenceDecisionMonthField;
            }
            set
            {
                this.ReferenceDecisionMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceStartMonth
        {
            get
            {
                return this.ReferenceStartMonthField;
            }
            set
            {
                this.ReferenceStartMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Refused
        {
            get
            {
                return this.RefusedField;
            }
            set
            {
                this.RefusedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessage", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetAccountResponseLsA2LJth))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetBOBDataResponse8RfXiUvf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetCertificatesResponse7nXz08R8))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetContactDataResponsextpbGwBg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetLettersResponse_Pp_PoQSnk))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetPaymentsResponseeBZTnTHy))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetPersonResponseTMmweO7p))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BobService.ReturnMessageOfGetPersonsByCertificateStateResponseQpig7IuX))]
    public partial class ReturnMessage : object
    {
        
        private BobService.Message[] BusinessMessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Message[] BusinessMessages
        {
            get
            {
                return this.BusinessMessagesField;
            }
            set
            {
                this.BusinessMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetAccountResponseLsA2LJth", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetAccountResponseLsA2LJth : BobService.ReturnMessage
    {
        
        private BobService.GetAccountResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetAccountResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetBOBDataResponse8RfXiUvf", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetBOBDataResponse8RfXiUvf : BobService.ReturnMessage
    {
        
        private BobService.GetBOBDataResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetBOBDataResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetCertificatesResponse7nXz08R8", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetCertificatesResponse7nXz08R8 : BobService.ReturnMessage
    {
        
        private BobService.GetCertificatesResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetCertificatesResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetContactDataResponsextpbGwBg", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetContactDataResponsextpbGwBg : BobService.ReturnMessage
    {
        
        private BobService.GetContactDataResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetContactDataResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetLettersResponse_Pp_PoQSnk", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetLettersResponse_Pp_PoQSnk : BobService.ReturnMessage
    {
        
        private BobService.GetLettersResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetLettersResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPaymentsResponseeBZTnTHy", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPaymentsResponseeBZTnTHy : BobService.ReturnMessage
    {
        
        private BobService.GetPaymentsResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetPaymentsResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPersonResponseTMmweO7p", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPersonResponseTMmweO7p : BobService.ReturnMessage
    {
        
        private BobService.GetPersonResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetPersonResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPersonsByCertificateStateResponseQpig7IuX", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPersonsByCertificateStateResponseQpig7IuX : BobService.ReturnMessage
    {
        
        private BobService.GetPersonsByCertificateStateResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.GetPersonsByCertificateStateResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class Message : object
    {
        
        private string MessageStringField;
        
        private BobService.MessageType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageString
        {
            get
            {
                return this.MessageStringField;
            }
            set
            {
                this.MessageStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.MessageType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByCertificateStateResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetPersonsByCertific" +
        "ateState")]
    public partial class GetPersonsByCertificateStateResponse : object
    {
        
        private long[] SinrsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Sinrs
        {
            get
            {
                return this.SinrsField;
            }
            set
            {
                this.SinrsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public enum MessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAccountResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetAccount")]
    public partial class GetAccountResponse : object
    {
        
        private BobService.Account AccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Account Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class Account : object
    {
        
        private string BicField;
        
        private string IbanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bic
        {
            get
            {
                return this.BicField;
            }
            set
            {
                this.BicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban
        {
            get
            {
                return this.IbanField;
            }
            set
            {
                this.IbanField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBOBDataResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetBOBData")]
    public partial class GetBOBDataResponse : object
    {
        
        private BobService.BOBData[] BOBDataField;
        
        private BobService.ContactData ContactDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.BOBData[] BOBData
        {
            get
            {
                return this.BOBDataField;
            }
            set
            {
                this.BOBDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.ContactData ContactData
        {
            get
            {
                return this.ContactDataField;
            }
            set
            {
                this.ContactDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactData", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class ContactData : object
    {
        
        private string EmailField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BOBData", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class BOBData : object
    {
        
        private BobService.Certificate CertificateField;
        
        private BobService.Letter[] LettersField;
        
        private BobService.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Certificate Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Letter[] Letters
        {
            get
            {
                return this.LettersField;
            }
            set
            {
                this.LettersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certificate", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class Certificate : object
    {
        
        private System.Nullable<System.DateTime> DecisionDateField;
        
        private BobService.TemporaryEndPayment EndPaymentField;
        
        private System.DateTime FromField;
        
        private string IdField;
        
        private string ReasonClosureField;
        
        private string StateField;
        
        private System.Nullable<System.DateTime> UntilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DecisionDate
        {
            get
            {
                return this.DecisionDateField;
            }
            set
            {
                this.DecisionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.TemporaryEndPayment EndPayment
        {
            get
            {
                return this.EndPaymentField;
            }
            set
            {
                this.EndPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonClosure
        {
            get
            {
                return this.ReasonClosureField;
            }
            set
            {
                this.ReasonClosureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Until
        {
            get
            {
                return this.UntilField;
            }
            set
            {
                this.UntilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Letter", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class Letter : object
    {
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class Payment : object
    {
        
        private BobService.Account AccountField;
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private System.DateTime PeriodEndField;
        
        private System.DateTime PeriodStartField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        private int UnCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Account Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodEnd
        {
            get
            {
                return this.PeriodEndField;
            }
            set
            {
                this.PeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodStart
        {
            get
            {
                return this.PeriodStartField;
            }
            set
            {
                this.PeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnCode
        {
            get
            {
                return this.UnCodeField;
            }
            set
            {
                this.UnCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemporaryEndPayment", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class TemporaryEndPayment : object
    {
        
        private System.DateTime FromField;
        
        private string ReasonField;
        
        private System.Nullable<System.DateTime> UntilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Until
        {
            get
            {
                return this.UntilField;
            }
            set
            {
                this.UntilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetCertificates")]
    public partial class GetCertificatesResponse : object
    {
        
        private BobService.Certificate[] CertificatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Certificate[] Certificates
        {
            get
            {
                return this.CertificatesField;
            }
            set
            {
                this.CertificatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContactDataResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetContactData")]
    public partial class GetContactDataResponse : object
    {
        
        private BobService.ContactData ContactDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.ContactData ContactData
        {
            get
            {
                return this.ContactDataField;
            }
            set
            {
                this.ContactDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLettersResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetLetters")]
    public partial class GetLettersResponse : object
    {
        
        private BobService.Letter[] LettersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Letter[] Letters
        {
            get
            {
                return this.LettersField;
            }
            set
            {
                this.LettersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetPayments")]
    public partial class GetPaymentsResponse : object
    {
        
        private BobService.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetPerson")]
    public partial class GetPersonResponse : object
    {
        
        private BobService.Person personField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Person person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class Person : object
    {
        
        private System.DateTime BirthDateField;
        
        private BobService.Account CurrentBOBAccountNrField;
        
        private int FederationNumberField;
        
        private string FirstNameField;
        
        private string InszField;
        
        private string NameField;
        
        private string NationalityField;
        
        private short SexField;
        
        private long SiNumberField;
        
        private BobService.ContactData contactDataField;
        
        private BobService.Address mainAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Account CurrentBOBAccountNr
        {
            get
            {
                return this.CurrentBOBAccountNrField;
            }
            set
            {
                this.CurrentBOBAccountNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FederationNumber
        {
            get
            {
                return this.FederationNumberField;
            }
            set
            {
                this.FederationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.ContactData contactData
        {
            get
            {
                return this.contactDataField;
            }
            set
            {
                this.contactDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BobService.Address mainAddress
        {
            get
            {
                return this.mainAddressField;
            }
            set
            {
                this.mainAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.Data")]
    public partial class Address : object
    {
        
        private string CountryField;
        
        private string HouseNumberField;
        
        private string LocalityField;
        
        private string NumberBoxField;
        
        private string StreetField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locality
        {
            get
            {
                return this.LocalityField;
            }
            set
            {
                this.LocalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberBox
        {
            get
            {
                return this.NumberBoxField;
            }
            set
            {
                this.NumberBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultDetail : object
    {
        
        private BobService.FaultMessage[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BobService.FaultMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultMessage : object
    {
        
        private string SourceField;
        
        private string TagField;
        
        private BobService.MessageText[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BobService.MessageText[] Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageText", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class MessageText : object
    {
        
        private string CultureField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetAccount")]
    public partial class GetAccountRequest : object
    {
        
        private long SiNumberField;
        
        private int federationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int federation
        {
            get
            {
                return this.federationField;
            }
            set
            {
                this.federationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBobDataRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetBOBData")]
    public partial class GetBobDataRequest : object
    {
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetCertificates")]
    public partial class GetCertificatesRequest : object
    {
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContactDataRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetContactData")]
    public partial class GetContactDataRequest : object
    {
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLettersRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetLetters")]
    public partial class GetLettersRequest : object
    {
        
        private string CertificateIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateId
        {
            get
            {
                return this.CertificateIdField;
            }
            set
            {
                this.CertificateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetPayments")]
    public partial class GetPaymentsRequest : object
    {
        
        private System.DateTime ReferenceDateField;
        
        private decimal SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.BOB.Contracts.GetPerson")]
    public partial class GetPersonRequest : object
    {
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12", ConfigurationName="BobService.IBobService")]
    public interface IBobService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPe" +
            "rsonsByCertificateState", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPe" +
            "rsonsByCertificateStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPe" +
            "rsonsByCertificateStateFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetPersonsByCertificateStateResponseQpig7IuX> GetPersonsByCertificateStateAsync(BobService.GetPersonsByCertificateStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetAc" +
            "count", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetAc" +
            "countResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetAc" +
            "countFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetAccountResponseLsA2LJth> GetAccountAsync(BobService.GetAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetBo" +
            "bData", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetBo" +
            "bDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetBo" +
            "bDataFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetBOBDataResponse8RfXiUvf> GetBobDataAsync(BobService.GetBobDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetCe" +
            "rtificates", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetCe" +
            "rtificatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetCe" +
            "rtificatesFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetCertificatesResponse7nXz08R8> GetCertificatesAsync(BobService.GetCertificatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetCo" +
            "ntactData", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetCo" +
            "ntactDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetCo" +
            "ntactDataFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetContactDataResponsextpbGwBg> GetContactDataAsync(BobService.GetContactDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetLe" +
            "tters", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetLe" +
            "ttersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetLe" +
            "ttersFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetLettersResponse_Pp_PoQSnk> GetLettersAsync(BobService.GetLettersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPa" +
            "yments", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPa" +
            "ymentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPa" +
            "ymentsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetPaymentsResponseeBZTnTHy> GetPaymentsAsync(BobService.GetPaymentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPe" +
            "rson", ReplyAction="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPe" +
            "rsonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BobService.FaultDetail), Action="http://MutSocMut/GW.VSB.BOB.Service.Contracts.Data/Data/2015/12/IBobService/GetPe" +
            "rsonFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<BobService.ReturnMessageOfGetPersonResponseTMmweO7p> GetPersonAsync(BobService.GetPersonRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IBobServiceChannel : BobService.IBobService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class BobServiceClient : System.ServiceModel.ClientBase<BobService.IBobService>, BobService.IBobService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BobServiceClient() : 
                base(BobServiceClient.GetDefaultBinding(), BobServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBobService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BobServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BobServiceClient.GetBindingForEndpoint(endpointConfiguration), BobServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BobServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BobServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BobServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BobServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetPersonsByCertificateStateResponseQpig7IuX> GetPersonsByCertificateStateAsync(BobService.GetPersonsByCertificateStateRequest request)
        {
            return base.Channel.GetPersonsByCertificateStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetAccountResponseLsA2LJth> GetAccountAsync(BobService.GetAccountRequest request)
        {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetBOBDataResponse8RfXiUvf> GetBobDataAsync(BobService.GetBobDataRequest request)
        {
            return base.Channel.GetBobDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetCertificatesResponse7nXz08R8> GetCertificatesAsync(BobService.GetCertificatesRequest request)
        {
            return base.Channel.GetCertificatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetContactDataResponsextpbGwBg> GetContactDataAsync(BobService.GetContactDataRequest request)
        {
            return base.Channel.GetContactDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetLettersResponse_Pp_PoQSnk> GetLettersAsync(BobService.GetLettersRequest request)
        {
            return base.Channel.GetLettersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetPaymentsResponseeBZTnTHy> GetPaymentsAsync(BobService.GetPaymentsRequest request)
        {
            return base.Channel.GetPaymentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BobService.ReturnMessageOfGetPersonResponseTMmweO7p> GetPersonAsync(BobService.GetPersonRequest request)
        {
            return base.Channel.GetPersonAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBobService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBobService))
            {
                return new System.ServiceModel.EndpointAddress("http://ws-test3.sm-ms.lan/GW.VSB.BOB.WcfService/WcfService/BobService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BobServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBobService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BobServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBobService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBobService,
        }
    }
}
