//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThabService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByCertificateStateRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonsByCertifi" +
        "cateState")]
    public partial class GetPersonsByCertificateStateRequest : object
    {
        
        private bool AcceptedField;
        
        private bool PendingField;
        
        private System.DateTime ReferenceDecisionMonthField;
        
        private System.DateTime ReferenceStartMonthField;
        
        private bool RefusedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Accepted
        {
            get
            {
                return this.AcceptedField;
            }
            set
            {
                this.AcceptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pending
        {
            get
            {
                return this.PendingField;
            }
            set
            {
                this.PendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDecisionMonth
        {
            get
            {
                return this.ReferenceDecisionMonthField;
            }
            set
            {
                this.ReferenceDecisionMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceStartMonth
        {
            get
            {
                return this.ReferenceStartMonthField;
            }
            set
            {
                this.ReferenceStartMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Refused
        {
            get
            {
                return this.RefusedField;
            }
            set
            {
                this.RefusedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessage", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetThabDataResponse8avSXHVx))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetCertificatesResponsefjFlgFUb))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetPaymentsResponsekH_Pn8jcG))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetLettersResponseRT_S2fO0f))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetPersonalDataResponser1i1MAcW))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetRemarkResponse5o92LdDq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfSaveRemarkResponseZnlGTFiS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ThabService.ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S))]
    public partial class ReturnMessage : object
    {
        
        private ThabService.Message[] BusinessMessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Message[] BusinessMessages
        {
            get
            {
                return this.BusinessMessagesField;
            }
            set
            {
                this.BusinessMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetThabDataResponse8avSXHVx", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetThabDataResponse8avSXHVx : ThabService.ReturnMessage
    {
        
        private ThabService.GetThabDataResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetThabDataResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetCertificatesResponsefjFlgFUb", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetCertificatesResponsefjFlgFUb : ThabService.ReturnMessage
    {
        
        private ThabService.GetCertificatesResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetCertificatesResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb : ThabService.ReturnMessage
    {
        
        private ThabService.GetCertificatesPayableAmountResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetCertificatesPayableAmountResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPaymentsResponsekH_Pn8jcG", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPaymentsResponsekH_Pn8jcG : ThabService.ReturnMessage
    {
        
        private ThabService.GetPaymentsResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetPaymentsResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetLettersResponseRT_S2fO0f", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetLettersResponseRT_S2fO0f : ThabService.ReturnMessage
    {
        
        private ThabService.GetLettersResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetLettersResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc : ThabService.ReturnMessage
    {
        
        private ThabService.GetCertificateNotificationsResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetCertificateNotificationsResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPersonalDataResponser1i1MAcW", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPersonalDataResponser1i1MAcW : ThabService.ReturnMessage
    {
        
        private ThabService.GetPersonalDataResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetPersonalDataResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetRemarkResponse5o92LdDq", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetRemarkResponse5o92LdDq : ThabService.ReturnMessage
    {
        
        private ThabService.GetRemarkResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetRemarkResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfSaveRemarkResponseZnlGTFiS", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfSaveRemarkResponseZnlGTFiS : ThabService.ReturnMessage
    {
        
        private ThabService.SaveRemarkResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.SaveRemarkResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S : ThabService.ReturnMessage
    {
        
        private ThabService.GetPersonsByCertificateStateResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.GetPersonsByCertificateStateResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public partial class Message : object
    {
        
        private string MessageStringField;
        
        private ThabService.MessageType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageString
        {
            get
            {
                return this.MessageStringField;
            }
            set
            {
                this.MessageStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.MessageType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonsByCertificateStateResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonsByCertifi" +
        "cateState")]
    public partial class GetPersonsByCertificateStateResponse : object
    {
        
        private long[] SinrsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Sinrs
        {
            get
            {
                return this.SinrsField;
            }
            set
            {
                this.SinrsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/GW.Core.Messaging")]
    public enum MessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetThabDataResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetThabData")]
    public partial class GetThabDataResponse : object
    {
        
        private ThabService.ThabData[] ThabDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.ThabData[] ThabData
        {
            get
            {
                return this.ThabDataField;
            }
            set
            {
                this.ThabDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThabData", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class ThabData : object
    {
        
        private ThabService.Certificate CertificateField;
        
        private ThabService.CertificateNotifications CertificateNotificationsField;
        
        private ThabService.Letter[] LettersField;
        
        private ThabService.CertificatePayableAmount[] PayableAmountsField;
        
        private ThabService.Payment[] PaymentsField;
        
        private string RemarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Certificate Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.CertificateNotifications CertificateNotifications
        {
            get
            {
                return this.CertificateNotificationsField;
            }
            set
            {
                this.CertificateNotificationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Letter[] Letters
        {
            get
            {
                return this.LettersField;
            }
            set
            {
                this.LettersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.CertificatePayableAmount[] PayableAmounts
        {
            get
            {
                return this.PayableAmountsField;
            }
            set
            {
                this.PayableAmountsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certificate", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Certificate : object
    {
        
        private ThabService.DocumentLink CalculationBasicRightDocumentField;
        
        private System.Nullable<System.DateTime> DecisionDateField;
        
        private System.Nullable<System.DateTime> FromField;
        
        private string IdField;
        
        private System.DateTime InitialDateField;
        
        private System.Nullable<System.DateTime> MigrateDateField;
        
        private string ReasonClosureField;
        
        private System.Nullable<System.DateTime> RegistrationDateField;
        
        private string StateField;
        
        private System.Nullable<System.DateTime> UntilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.DocumentLink CalculationBasicRightDocument
        {
            get
            {
                return this.CalculationBasicRightDocumentField;
            }
            set
            {
                this.CalculationBasicRightDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DecisionDate
        {
            get
            {
                return this.DecisionDateField;
            }
            set
            {
                this.DecisionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitialDate
        {
            get
            {
                return this.InitialDateField;
            }
            set
            {
                this.InitialDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MigrateDate
        {
            get
            {
                return this.MigrateDateField;
            }
            set
            {
                this.MigrateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonClosure
        {
            get
            {
                return this.ReasonClosureField;
            }
            set
            {
                this.ReasonClosureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Until
        {
            get
            {
                return this.UntilField;
            }
            set
            {
                this.UntilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificateNotifications", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class CertificateNotifications : object
    {
        
        private ThabService.NextStep nextStepField;
        
        private ThabService.Notification[] notificicationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.NextStep nextStep
        {
            get
            {
                return this.nextStepField;
            }
            set
            {
                this.nextStepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Notification[] notificications
        {
            get
            {
                return this.notificicationsField;
            }
            set
            {
                this.notificicationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Letter", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Letter : object
    {
        
        private string CertificateIdField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateId
        {
            get
            {
                return this.CertificateIdField;
            }
            set
            {
                this.CertificateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificatePayableAmount", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class CertificatePayableAmount : object
    {
        
        private decimal AmountField;
        
        private System.Nullable<System.DateTime> EndField;
        
        private System.Nullable<System.DateTime> StartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Payment : object
    {
        
        private ThabService.Account AccountField;
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private System.DateTime PeriodEndField;
        
        private System.DateTime PeriodStartField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        private int UnCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Account Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodEnd
        {
            get
            {
                return this.PeriodEndField;
            }
            set
            {
                this.PeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodStart
        {
            get
            {
                return this.PeriodStartField;
            }
            set
            {
                this.PeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnCode
        {
            get
            {
                return this.UnCodeField;
            }
            set
            {
                this.UnCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentLink", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class DocumentLink : object
    {
        
        private string ReferenceField;
        
        private string UniqueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueId
        {
            get
            {
                return this.UniqueIdField;
            }
            set
            {
                this.UniqueIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NextStep", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class NextStep : object
    {
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Notification : object
    {
        
        private string CodeField;
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class Account : object
    {
        
        private string BicField;
        
        private string IbanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bic
        {
            get
            {
                return this.BicField;
            }
            set
            {
                this.BicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban
        {
            get
            {
                return this.IbanField;
            }
            set
            {
                this.IbanField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesResponse : object
    {
        
        private ThabService.Certificate[] CertificatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Certificate[] Certificates
        {
            get
            {
                return this.CertificatesField;
            }
            set
            {
                this.CertificatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesPayableAmountResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesPayableAmountResponse : object
    {
        
        private ThabService.CertificatePayableAmount[] PayableAmountsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.CertificatePayableAmount[] PayableAmounts
        {
            get
            {
                return this.PayableAmountsField;
            }
            set
            {
                this.PayableAmountsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPayments")]
    public partial class GetPaymentsResponse : object
    {
        
        private ThabService.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLettersResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Core.Read.GetLetters")]
    public partial class GetLettersResponse : object
    {
        
        private ThabService.Letter[] LettersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.Letter[] Letters
        {
            get
            {
                return this.LettersField;
            }
            set
            {
                this.LettersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificateNotificationsResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificateNotif" +
        "ications")]
    public partial class GetCertificateNotificationsResponse : object
    {
        
        private ThabService.CertificateNotifications CertificateNotificationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.CertificateNotifications CertificateNotifications
        {
            get
            {
                return this.CertificateNotificationsField;
            }
            set
            {
                this.CertificateNotificationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonalDataResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonalData")]
    public partial class GetPersonalDataResponse : object
    {
        
        private ThabService.PersonalData PersonalDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThabService.PersonalData PersonalData
        {
            get
            {
                return this.PersonalDataField;
            }
            set
            {
                this.PersonalDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalData", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.Data")]
    public partial class PersonalData : object
    {
        
        private string CityContactField;
        
        private int FederationField;
        
        private string FirstNameContactField;
        
        private string FirstNameMemberField;
        
        private short GenderMemberField;
        
        private string HouseNumberContactField;
        
        private string InszField;
        
        private string NameContactField;
        
        private string NameMemberField;
        
        private string NumberBoxContactField;
        
        private long SiNumberField;
        
        private string StreetContactField;
        
        private string ZipCodeContactField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityContact
        {
            get
            {
                return this.CityContactField;
            }
            set
            {
                this.CityContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Federation
        {
            get
            {
                return this.FederationField;
            }
            set
            {
                this.FederationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameContact
        {
            get
            {
                return this.FirstNameContactField;
            }
            set
            {
                this.FirstNameContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameMember
        {
            get
            {
                return this.FirstNameMemberField;
            }
            set
            {
                this.FirstNameMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short GenderMember
        {
            get
            {
                return this.GenderMemberField;
            }
            set
            {
                this.GenderMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumberContact
        {
            get
            {
                return this.HouseNumberContactField;
            }
            set
            {
                this.HouseNumberContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameContact
        {
            get
            {
                return this.NameContactField;
            }
            set
            {
                this.NameContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameMember
        {
            get
            {
                return this.NameMemberField;
            }
            set
            {
                this.NameMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberBoxContact
        {
            get
            {
                return this.NumberBoxContactField;
            }
            set
            {
                this.NumberBoxContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetContact
        {
            get
            {
                return this.StreetContactField;
            }
            set
            {
                this.StreetContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCodeContact
        {
            get
            {
                return this.ZipCodeContactField;
            }
            set
            {
                this.ZipCodeContactField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRemarkResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetRemark")]
    public partial class GetRemarkResponse : object
    {
        
        private string RemarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRemarkResponse", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.SaveRemark")]
    public partial class SaveRemarkResponse : object
    {
        
        private bool SavedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Saved
        {
            get
            {
                return this.SavedField;
            }
            set
            {
                this.SavedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultDetail : object
    {
        
        private ThabService.FaultMessage[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ThabService.FaultMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class FaultMessage : object
    {
        
        private string SourceField;
        
        private string TagField;
        
        private ThabService.MessageText[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ThabService.MessageText[] Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageText", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
    public partial class MessageText : object
    {
        
        private string CultureField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetThabDataRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetThabData")]
    public partial class GetThabDataRequest : object
    {
        
        private string InszField;
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesRequest : object
    {
        
        private string InszField;
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insz
        {
            get
            {
                return this.InszField;
            }
            set
            {
                this.InszField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificatesPayableAmountRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificates")]
    public partial class GetCertificatesPayableAmountRequest : object
    {
        
        private string IdField;
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaymentsRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPayments")]
    public partial class GetPaymentsRequest : object
    {
        
        private System.DateTime ReferenceDateField;
        
        private decimal SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLettersRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Core.Read.GetLetters")]
    public partial class GetLettersRequest : object
    {
        
        private string CertificateIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateId
        {
            get
            {
                return this.CertificateIdField;
            }
            set
            {
                this.CertificateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertificateNotificationsRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetCertificateNotif" +
        "ications")]
    public partial class GetCertificateNotificationsRequest : object
    {
        
        private string CertificateIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateId
        {
            get
            {
                return this.CertificateIdField;
            }
            set
            {
                this.CertificateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonalDataRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetPersonalData")]
    public partial class GetPersonalDataRequest : object
    {
        
        private long SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRemarkRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.GetRemark")]
    public partial class GetRemarkRequest : object
    {
        
        private System.DateTime ReferenceDateField;
        
        private decimal SiNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SiNumber
        {
            get
            {
                return this.SiNumberField;
            }
            set
            {
                this.SiNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRemarkRequest", Namespace="http://schemas.datacontract.org/2004/07/GW.VSB.THAB.Contracts.SaveRemark")]
    public partial class SaveRemarkRequest : object
    {
        
        private System.DateTime ReferenceDateField;
        
        private string RemarkField;
        
        private long SinrField;
        
        private string UseridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Sinr
        {
            get
            {
                return this.SinrField;
            }
            set
            {
                this.SinrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Userid
        {
            get
            {
                return this.UseridField;
            }
            set
            {
                this.UseridField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12", ConfigurationName="ThabService.IThabService")]
    public interface IThabService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PersonsByCertificateState", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PersonsByCertificateStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PersonsByCertificateStateFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S> GetPersonsByCertificateStateAsync(ThabService.GetPersonsByCertificateStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "ThabData", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "ThabDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "ThabDataFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetThabDataResponse8avSXHVx> GetThabDataAsync(ThabService.GetThabDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "Certificates", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificatesFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetCertificatesResponsefjFlgFUb> GetCertificatesAsync(ThabService.GetCertificatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificatesPayableAmounts", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificatesPayableAmountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificatesPayableAmountsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb> GetCertificatesPayableAmountsAsync(ThabService.GetCertificatesPayableAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "Payments", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PaymentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PaymentsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetPaymentsResponsekH_Pn8jcG> GetPaymentsAsync(ThabService.GetPaymentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "Letters", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "LettersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "LettersFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetLettersResponseRT_S2fO0f> GetLettersAsync(ThabService.GetLettersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificateNotifications", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificateNotificationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "CertificateNotificationsFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc> GetCertificateNotificationsAsync(ThabService.GetCertificateNotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PersonalData", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PersonalDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "PersonalDataFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetPersonalDataResponser1i1MAcW> GetPersonalDataAsync(ThabService.GetPersonalDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "Remark", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "RemarkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Get" +
            "RemarkFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetRemarkResponse5o92LdDq> GetRemarkAsync(ThabService.GetRemarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Sav" +
            "eRemark", ReplyAction="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Sav" +
            "eRemarkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ThabService.FaultDetail), Action="http://MutSocMut/GW.VSB.THAB.Service.Contracts.Data/Data/2016/12/IThabService/Sav" +
            "eRemarkFaultDetailFault", Name="FaultDetail", Namespace="http://www.socmut.be/ErrorHandling/2008/05")]
        System.Threading.Tasks.Task<ThabService.ReturnMessageOfSaveRemarkResponseZnlGTFiS> SaveRemarkAsync(ThabService.SaveRemarkRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IThabServiceChannel : ThabService.IThabService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class ThabServiceClient : System.ServiceModel.ClientBase<ThabService.IThabService>, ThabService.IThabService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ThabServiceClient() : 
                base(ThabServiceClient.GetDefaultBinding(), ThabServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IThabService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThabServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ThabServiceClient.GetBindingForEndpoint(endpointConfiguration), ThabServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThabServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ThabServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThabServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ThabServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThabServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetPersonsByCertificateStateResponse4xuWB6v_S> GetPersonsByCertificateStateAsync(ThabService.GetPersonsByCertificateStateRequest request)
        {
            return base.Channel.GetPersonsByCertificateStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetThabDataResponse8avSXHVx> GetThabDataAsync(ThabService.GetThabDataRequest request)
        {
            return base.Channel.GetThabDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetCertificatesResponsefjFlgFUb> GetCertificatesAsync(ThabService.GetCertificatesRequest request)
        {
            return base.Channel.GetCertificatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetCertificatesPayableAmountResponsefjFlgFUb> GetCertificatesPayableAmountsAsync(ThabService.GetCertificatesPayableAmountRequest request)
        {
            return base.Channel.GetCertificatesPayableAmountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetPaymentsResponsekH_Pn8jcG> GetPaymentsAsync(ThabService.GetPaymentsRequest request)
        {
            return base.Channel.GetPaymentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetLettersResponseRT_S2fO0f> GetLettersAsync(ThabService.GetLettersRequest request)
        {
            return base.Channel.GetLettersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetCertificateNotificationsResponsesRGO4oBc> GetCertificateNotificationsAsync(ThabService.GetCertificateNotificationsRequest request)
        {
            return base.Channel.GetCertificateNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetPersonalDataResponser1i1MAcW> GetPersonalDataAsync(ThabService.GetPersonalDataRequest request)
        {
            return base.Channel.GetPersonalDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfGetRemarkResponse5o92LdDq> GetRemarkAsync(ThabService.GetRemarkRequest request)
        {
            return base.Channel.GetRemarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThabService.ReturnMessageOfSaveRemarkResponseZnlGTFiS> SaveRemarkAsync(ThabService.SaveRemarkRequest request)
        {
            return base.Channel.SaveRemarkAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IThabService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IThabService))
            {
                return new System.ServiceModel.EndpointAddress("http://ws-test3.sm-ms.lan/GW.VSB.THAB.WcfService/WcfService/ThabService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ThabServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IThabService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ThabServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IThabService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IThabService,
        }
    }
}
